### PR TITLE
feat: (action) Cache node modules

### PR DESCRIPTION
**Pull request by h7ml**
feat: (action) Cache node modules

### CODE REVIEW

**Comment by h7ml** [comment]
Use caching to speed up the build of actions. Improved dependency package installation time by approximately 60%

**Comment by h7ml** [comment]
> Use caching to speed up the build of actions. Improved dependency package installation time by approximately 60%

image

**Comment by YunYouJun** [comment]
We didn't add a dependency to it before, partly because we didn't want to pin a package manager.

`package-lock.json` / `yarn.lock` / `pnpm-lock.yaml`

**Comment by sxzz** [comment]
As a starter / template, I think the better way is to ignore or exclude lock file, and then the template is always up-to-date. Besides, I don't think we should make a specific package manager as default. It's up to users.

**Comment by YunYouJun** [comment]
For now, it may not be necessary, but if caching is needed, I actually prefer PNPM, which has a smaller and faster lockfile.

**Pull request closed without merging**
